spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: product
          uri: http://localhost:8085
          predicates:
            - Path=/products/**
        - id: user
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
        - id: redis
          uri: http://localhost:8080
          predicates:
            - Path=/redis/**
        - id: jwt
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**